name: ci

on:
  push:
    branches: [main, master]
    tags: ['*']

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Switch git branch
        run: |
          git config --local user.name '$GITHUB_ACTOR'
          git config --local user.email '$GITHUB_ACTOR@users.noreply.github.com'
        shell: bash

      - name: Build and publish
        run: |
          workflowr::wflow_git_config()
          workflowr::wflow_build()
          workflowr::wflow_publish(republish = TRUE)
        shell: Rscript {0}

      - name: Commit to gh-pages
        run: |
          git add ./
          git commit -m 'Updated workflowr site via GitHub Actions'
          git push -f origin master:gh-pages
        shell: bash
